-- MySQL Script generated by MySQL Workbench
-- Wed Apr 10 18:28:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(60) NULL,
  `rol` INT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `typo` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `num interior` VARCHAR(45) NULL,
  `num exterior` VARCHAR(45) NULL,
  `colonia` VARCHAR(45) NULL,
  `municipio` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cp` VARCHAR(45) NULL,
  PRIMARY KEY (`idDireccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `appaterno` VARCHAR(45) NULL,
  `apmaterno` VARCHAR(45) NULL,
  `fechanac` DATE NULL,
  `lugarnac` VARCHAR(45) NULL,
  `estadocivil` VARCHAR(45) NULL,
  `curp` VARCHAR(45) NULL,
  `gruposan` VARCHAR(45) NULL,
  `telefono fijo` VARCHAR(45) NULL,
  `telefono celular` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `escolaridad` VARCHAR(45) NULL,
  `direccion` INT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `dir_idx` (`direccion` ASC),
  CONSTRAINT `dir`
    FOREIGN KEY (`direccion`)
    REFERENCES `mydb`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CentrodeTrabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CentrodeTrabajo` (
  `idCentrodeTrabajo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` INT NULL,
  PRIMARY KEY (`idCentrodeTrabajo`),
  INDEX `dir_idx` (`direccion` ASC),
  CONSTRAINT `dir`
    FOREIGN KEY (`direccion`)
    REFERENCES `mydb`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trabajadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trabajadora` (
  `idtrabajadora` INT NOT NULL AUTO_INCREMENT,
  `persona` INT NULL,
  `numtrabajador` INT NULL,
  `sueldomensual` FLOAT NULL,
  `horasalida` TIME NULL,
  `ocupacion` VARCHAR(45) NULL,
  `puesto` VARCHAR(45) NULL,
  `adscripcion` VARCHAR(45) NULL,
  `horaentrada` TIME NULL,
  `centrodetrabajo` INT NULL,
  `telefonooficina` VARCHAR(45) NULL,
  `extencionoficina` VARCHAR(45) NULL,
  `jefe` VARCHAR(45) NULL,
  `cargojefe` VARCHAR(45) NULL,
  `usuario` INT NULL,
  PRIMARY KEY (`idtrabajadora`),
  INDEX `ess_idx` (`persona` ASC),
  INDEX `centro_idx` (`centrodetrabajo` ASC),
  INDEX `us_idx` (`usuario` ASC),
  CONSTRAINT `ess`
    FOREIGN KEY (`persona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `centro`
    FOREIGN KEY (`centrodetrabajo`)
    REFERENCES `mydb`.`CentrodeTrabajo` (`idCentrodeTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `us`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Padre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Padre` (
  `idPadre` INT NOT NULL AUTO_INCREMENT,
  `persona` INT NULL,
  PRIMARY KEY (`idPadre`),
  INDEX `ess_idx` (`persona` ASC),
  CONSTRAINT `ess`
    FOREIGN KEY (`persona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PersonaAutorizada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PersonaAutorizada` (
  `idPersonaAutorizada` INT NOT NULL AUTO_INCREMENT,
  `persona` INT NULL,
  `ocupacion` VARCHAR(45) NULL,
  `parentesco` VARCHAR(45) NULL,
  `PersonaAutorizadacol` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersonaAutorizada`),
  INDEX `es_idx` (`persona` ASC),
  CONSTRAINT `es`
    FOREIGN KEY (`persona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiante` (
  `idestudiante` INT NOT NULL AUTO_INCREMENT,
  `persona` INT NULL,
  `madre` INT NULL,
  `padre` INT NULL,
  `personaautorizada` INT NULL,
  `folio` VARCHAR(45) NULL,
  `cendi` INT NULL,
  `grupo` INT NULL,
  PRIMARY KEY (`idestudiante`),
  INDEX `es_idx` (`persona` ASC),
  INDEX `madre_idx` (`madre` ASC),
  INDEX `padre_idx` (`padre` ASC),
  INDEX `perauto_idx` (`personaautorizada` ASC),
  CONSTRAINT `es`
    FOREIGN KEY (`persona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `madre`
    FOREIGN KEY (`madre`)
    REFERENCES `mydb`.`Trabajadora` (`idtrabajadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `padre`
    FOREIGN KEY (`padre`)
    REFERENCES `mydb`.`Padre` (`idPadre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `perauto`
    FOREIGN KEY (`personaautorizada`)
    REFERENCES `mydb`.`PersonaAutorizada` (`idPersonaAutorizada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cendi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cendi` (
  `idCendi` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `directora` VARCHAR(45) NULL,
  `direccion` INT NULL,
  PRIMARY KEY (`idCendi`),
  INDEX `dir_idx` (`direccion` ASC),
  CONSTRAINT `dir`
    FOREIGN KEY (`direccion`)
    REFERENCES `mydb`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grupo` (
  `idGrupo` INT NOT NULL AUTO_INCREMENT,
  `nombregrupo` VARCHAR(45) NULL,
  `cendi` INT NULL,
  `capacidad` INT NULL,
  `siguiente` INT NULL,
  PRIMARY KEY (`idGrupo`),
  INDEX `estaen_idx` (`cendi` ASC),
  INDEX `sig_idx` (`siguiente` ASC),
  CONSTRAINT `estaen`
    FOREIGN KEY (`cendi`)
    REFERENCES `mydb`.`Cendi` (`idCendi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sig`
    FOREIGN KEY (`siguiente`)
    REFERENCES `mydb`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inscripcion` (
  `idinscripcion` INT NOT NULL,
  `idestudiante` INT NULL,
  `fechaingreso` DATE NULL,
  `fechaalta` VARCHAR(45) NULL,
  `cicloescolar` VARCHAR(45) NULL,
  `cendi` INT NULL,
  `grupo` INT NULL,
  `inscripcionanterior` INT NULL,
  `fechaegreso` DATE NULL,
  `estatus` INT NULL,
  `observaciones` TEXT NULL,
  PRIMARY KEY (`idinscripcion`),
  INDEX `estudia_idx` (`idestudiante` ASC),
  INDEX `cendi_idx` (`cendi` ASC),
  INDEX `grupo_idx` (`grupo` ASC),
  CONSTRAINT `estudia`
    FOREIGN KEY (`idestudiante`)
    REFERENCES `mydb`.`Estudiante` (`idestudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cendi`
    FOREIGN KEY (`cendi`)
    REFERENCES `mydb`.`Cendi` (`idCendi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `grupo`
    FOREIGN KEY (`grupo`)
    REFERENCES `mydb`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cambio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cambio` (
  `idCambio` INT NOT NULL AUTO_INCREMENT,
  `incripcionanterior` INT NULL,
  `incripcionnueva` INT NULL,
  `fechasoliitud` DATE NULL,
  `fechaaprovacion` DATE NULL,
  `motivo` TEXT NULL,
  INDEX `anterior_idx` (`incripcionanterior` ASC),
  INDEX `nueva_idx` (`incripcionnueva` ASC),
  CONSTRAINT `anterior`
    FOREIGN KEY (`incripcionanterior`)
    REFERENCES `mydb`.`Inscripcion` (`idinscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nueva`
    FOREIGN KEY (`incripcionnueva`)
    REFERENCES `mydb`.`Inscripcion` (`idinscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Baja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Baja` (
  `idBaja` INT NOT NULL AUTO_INCREMENT,
  `inscripcion` INT NULL,
  `fechasolicitud` DATE NULL,
  `fechaaprovacion` DATE NULL,
  `motivo` TEXT NULL,
  INDEX `inscrip_idx` (`inscripcion` ASC),
  CONSTRAINT `inscrip`
    FOREIGN KEY (`inscripcion`)
    REFERENCES `mydb`.`Inscripcion` (`idinscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Procesoinscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Procesoinscripcion` (
  `idprocesoinscripcion` INT NOT NULL AUTO_INCREMENT,
  `inscripcion` INT NULL,
  `estado` INT NULL,
  `observaciones` TEXT NULL,
  `opcionA` INT NULL,
  `opcionB` INT NULL,
  `opcionC` INT NULL,
  PRIMARY KEY (`idprocesoinscripcion`),
  INDEX `ins_idx` (`inscripcion` ASC),
  CONSTRAINT `ins`
    FOREIGN KEY (`inscripcion`)
    REFERENCES `mydb`.`Inscripcion` (`idinscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ValidacionporArea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ValidacionporArea` (
  `idValidacionporArea` INT NOT NULL AUTO_INCREMENT,
  `procesoinscripcion` INT NULL,
  `area` INT NULL,
  `estado` INT NULL,
  `fecha` DATE NULL,
  `observaciones` TEXT NULL,
  `validacioncocendi` INT NULL,
  INDEX `proce_idx` (`procesoinscripcion` ASC),
  CONSTRAINT `proce`
    FOREIGN KEY (`procesoinscripcion`)
    REFERENCES `mydb`.`Procesoinscripcion` (`idprocesoinscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmpleadoInstutucional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EmpleadoInstutucional` (
  `idEmpleadoInstutucional` INT NOT NULL AUTO_INCREMENT,
  `persona` INT NULL,
  `rol` VARCHAR(45) NULL,
  `area` VARCHAR(45) NULL,
  `dependencia` VARCHAR(45) NULL,
  `usuario` INT NULL,
  PRIMARY KEY (`idEmpleadoInstutucional`),
  INDEX `us_idx` (`usuario` ASC),
  INDEX `per_idx` (`persona` ASC),
  CONSTRAINT `us`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `per`
    FOREIGN KEY (`persona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LogAct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LogAct` (
  `idLogAct` INT NOT NULL,
  `accion` VARCHAR(45) NULL,
  `usuarioActor` INT NULL,
  `tiporeferencia` VARCHAR(45) NULL,
  `referencia` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  `ip` VARCHAR(45) NULL,
  `info` TEXT NULL,
  PRIMARY KEY (`idLogAct`),
  INDEX `us_idx` (`usuarioActor` ASC),
  CONSTRAINT `us`
    FOREIGN KEY (`usuarioActor`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

